name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --globl user.email 'github-actions[bot]@users.noreply.github.com'
  
    - name: Sync to dev
      run: |
        git checkout dev
        git pull origin dev
        git merge main
        git push origin dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}